package orchestrator

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/tsumina/dango/internal/layout"
	"github.com/tsumina/dango/internal/runtime"
	"github.com/tsumina/dango/internal/store/sqlite"
)

func TestDemoEngineRunEndToEndWithHostRuntime(t *testing.T) {
	root := t.TempDir()
	toolsRoot := filepath.Join(root, "tools")
	for _, tool := range []struct {
		Name        string
		InputType   string
		OutputType  string
		NextToolYML string
		OutputFile  string
	}{
		{Name: "toy-brief", InputType: "request", OutputType: "brief", NextToolYML: `"toy-drafter"`, OutputFile: "brief.md"},
		{Name: "toy-drafter", InputType: "brief", OutputType: "draft", NextToolYML: `"toy-packager"`, OutputFile: "draft.md"},
		{Name: "toy-packager", InputType: "draft", OutputType: "final", NextToolYML: "null", OutputFile: "final-report.md"},
	} {
		createTempTool(t, toolsRoot, tool.Name, tool.InputType, tool.OutputType, tool.NextToolYML, tool.OutputFile)
	}

	layout, err := layout.New(filepath.Join(root, "data"))
	if err != nil {
		t.Fatalf("layout.New() error = %v", err)
	}
	if err := layout.Ensure(); err != nil {
		t.Fatalf("layout.Ensure() error = %v", err)
	}

	store, err := sqlite.Open(layout.DBPath())
	if err != nil {
		t.Fatalf("sqlite.Open() error = %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })

	rt := runtime.NewDefault("")
	registry := NewRegistryService(layout, store, rt)
	for _, name := range []string{"toy-brief", "toy-drafter", "toy-packager"} {
		if _, err := registry.Register(context.Background(), runtime.HostPrefix+filepath.Join(toolsRoot, name), ""); err != nil {
			t.Fatalf("Register(%s) error = %v", name, err)
		}
	}

	taskService := NewTaskService(layout, store)
	planner := NewPlanner(store)
	scheduler := NewScheduler(layout, store, rt)
	engine := NewDemoEngine(layout, store, taskService, planner, scheduler)

	result, err := engine.Run(context.Background(), "write a small demo artifact")
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	if got, want := result.Task.Status, "done"; got != want {
		t.Fatalf("result.Task.Status = %q, want %q", got, want)
	}
	if got, want := len(result.Plan.Edges), 3; got != want {
		t.Fatalf("len(result.Plan.Edges) = %d, want %d", got, want)
	}
	if got, want := len(result.TerminalHandoffs), 1; got != want {
		t.Fatalf("len(result.TerminalHandoffs) = %d, want %d", got, want)
	}

	if _, err := os.Stat(result.ResultPath); err != nil {
		t.Fatalf("result.ResultPath stat error = %v", err)
	}

	finalEdgeID := result.Plan.Edges[len(result.Plan.Edges)-1].ID
	finalArtifact := filepath.Join(layout.EdgeOutputDir(result.Task.ID, finalEdgeID), "final-report.md")
	if _, err := os.Stat(finalArtifact); err != nil {
		t.Fatalf("final artifact stat error = %v", err)
	}
}

func createTempTool(t *testing.T, root, name, inputType, outputType, nextToolYAML, outputFile string) {
	t.Helper()

	toolDir := filepath.Join(root, name)
	if err := os.MkdirAll(toolDir, 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", toolDir, err)
	}

	toolYAML := fmt.Sprintf(`name: "%s"
version: "0.1.0"
description: "temp test tool %s"
input_types: ["%s"]
output_types: ["%s"]
model: "demo/%s"
`, name, name, inputType, outputType, name)
	if err := os.WriteFile(filepath.Join(toolDir, "tool.yaml"), []byte(toolYAML), 0o644); err != nil {
		t.Fatalf("write tool.yaml error = %v", err)
	}

	runScript := fmt.Sprintf(`#!/bin/sh
set -eu
timestamp="$(date -u +"%%Y-%%m-%%dT%%H:%%M:%%SZ")"
mkdir -p "${OUTPUT_PATH}"
cat > "${OUTPUT_PATH}/%s" <<EOF
generated by %s
EOF
cat > "${OUTPUT_PATH}/_handoff.md" <<EOF
---
task_id: "${TASK_ID}"
tool: "%s"
status: "completed"
output_files:
  - %s
next_tool: %s
timestamp: "${timestamp}"
---

## Description

Generated %s.
EOF
`, outputFile, name, name, outputFile, nextToolYAML, outputFile)
	runPath := filepath.Join(toolDir, "run")
	if err := os.WriteFile(runPath, []byte(runScript), 0o755); err != nil {
		t.Fatalf("write run script error = %v", err)
	}
	if err := os.Chmod(runPath, 0o755); err != nil {
		t.Fatalf("chmod run script error = %v", err)
	}
}
