// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, status, request, dag_json)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
`

type CreateTaskParams struct {
	ID      string         `json:"id"`
	Status  string         `json:"status"`
	Request sql.NullString `json:"request"`
	DagJson sql.NullString `json:"dag_json"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.Status,
		arg.Request,
		arg.DagJson,
	)
	return err
}

const deleteRunnerRecords = `-- name: DeleteRunnerRecords :execrows
DELETE FROM runner_records
WHERE runner_id = ?1
`

func (q *Queries) DeleteRunnerRecords(ctx context.Context, runnerID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunnerRecords, runnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTool = `-- name: DeleteTool :execrows
DELETE FROM tools
WHERE name = ?1
`

func (q *Queries) DeleteTool(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTool, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRunnerRecordState = `-- name: GetRunnerRecordState :one
SELECT
  CAST(COALESCE(MAX(sequence_number), 0) AS INTEGER) AS last_sequence_number,
  CAST(COALESCE(MAX(CASE WHEN kind = 'init' THEN 1 ELSE 0 END), 0) AS INTEGER) AS has_init
FROM runner_records
WHERE runner_id = ?1
`

type GetRunnerRecordStateRow struct {
	LastSequenceNumber int64 `json:"last_sequence_number"`
	HasInit            int64 `json:"has_init"`
}

func (q *Queries) GetRunnerRecordState(ctx context.Context, runnerID string) (GetRunnerRecordStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRunnerRecordState, runnerID)
	var i GetRunnerRecordStateRow
	err := row.Scan(&i.LastSequenceNumber, &i.HasInit)
	return i, err
}

const getSnapshotCursor = `-- name: GetSnapshotCursor :one
SELECT request_id, runner_id, checkpoint_sequence, event_sequence, updated_at
FROM snapshot_cursors
WHERE request_id = ?1
LIMIT 1
`

func (q *Queries) GetSnapshotCursor(ctx context.Context, requestID string) (SnapshotCursor, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotCursor, requestID)
	var i SnapshotCursor
	err := row.Scan(
		&i.RequestID,
		&i.RunnerID,
		&i.CheckpointSequence,
		&i.EventSequence,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, status, request, dag_json, created, updated
FROM tasks
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Request,
		&i.DagJson,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getTool = `-- name: GetTool :one
SELECT name, image, config_json, registered
FROM tools
WHERE name = ?1
LIMIT 1
`

func (q *Queries) GetTool(ctx context.Context, name string) (Tool, error) {
	row := q.db.QueryRowContext(ctx, getTool, name)
	var i Tool
	err := row.Scan(
		&i.Name,
		&i.Image,
		&i.ConfigJson,
		&i.Registered,
	)
	return i, err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO logs (edge_id, level, message)
VALUES (?1, ?2, ?3)
`

type InsertLogParams struct {
	EdgeID  string `json:"edge_id"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog, arg.EdgeID, arg.Level, arg.Message)
	return err
}

const insertRequestStreamEvent = `-- name: InsertRequestStreamEvent :exec
INSERT INTO request_stream_events (
  request_id,
  sequence_number,
  logical_time,
  event_type,
  source_layer,
  source_id,
  source_parent_id,
  runner_id,
  node_id,
  session_id,
  status,
  timestamp,
  raw_event_json
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13
)
`

type InsertRequestStreamEventParams struct {
	RequestID      string         `json:"request_id"`
	SequenceNumber int64          `json:"sequence_number"`
	LogicalTime    int64          `json:"logical_time"`
	EventType      string         `json:"event_type"`
	SourceLayer    string         `json:"source_layer"`
	SourceID       sql.NullString `json:"source_id"`
	SourceParentID sql.NullString `json:"source_parent_id"`
	RunnerID       sql.NullString `json:"runner_id"`
	NodeID         sql.NullString `json:"node_id"`
	SessionID      sql.NullString `json:"session_id"`
	Status         string         `json:"status"`
	Timestamp      string         `json:"timestamp"`
	RawEventJson   string         `json:"raw_event_json"`
}

func (q *Queries) InsertRequestStreamEvent(ctx context.Context, arg InsertRequestStreamEventParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestStreamEvent,
		arg.RequestID,
		arg.SequenceNumber,
		arg.LogicalTime,
		arg.EventType,
		arg.SourceLayer,
		arg.SourceID,
		arg.SourceParentID,
		arg.RunnerID,
		arg.NodeID,
		arg.SessionID,
		arg.Status,
		arg.Timestamp,
		arg.RawEventJson,
	)
	return err
}

const insertRunnerRecord = `-- name: InsertRunnerRecord :exec
INSERT INTO runner_records (
  runner_id,
  sequence_number,
  kind,
  timestamp,
  record_json
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
`

type InsertRunnerRecordParams struct {
	RunnerID       string `json:"runner_id"`
	SequenceNumber int64  `json:"sequence_number"`
	Kind           string `json:"kind"`
	Timestamp      string `json:"timestamp"`
	RecordJson     string `json:"record_json"`
}

func (q *Queries) InsertRunnerRecord(ctx context.Context, arg InsertRunnerRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertRunnerRecord,
		arg.RunnerID,
		arg.SequenceNumber,
		arg.Kind,
		arg.Timestamp,
		arg.RecordJson,
	)
	return err
}

const listRequestStreamEvents = `-- name: ListRequestStreamEvents :many
SELECT sequence_number, raw_event_json
FROM request_stream_events
WHERE request_id = ?1
  AND sequence_number >= ?2
  AND (?3 IS NULL OR runner_id = ?3)
  AND (?4 IS NULL OR node_id = ?4)
  AND (?5 IS NULL OR session_id = ?5)
  AND (?6 IS NULL OR status = ?6)
  AND (?7 IS NULL OR event_type = ?7)
  AND (?8 IS NULL OR event_type LIKE ?8 || '%')
  AND (?9 IS NULL OR source_layer = ?9)
  AND (?10 IS NULL OR source_id = ?10)
  AND (?11 IS NULL OR source_parent_id = ?11)
ORDER BY sequence_number ASC
`

type ListRequestStreamEventsParams struct {
	RequestID          string      `json:"request_id"`
	FromSequenceNumber int64       `json:"from_sequence_number"`
	RunnerID           interface{} `json:"runner_id"`
	NodeID             interface{} `json:"node_id"`
	SessionID          interface{} `json:"session_id"`
	Status             interface{} `json:"status"`
	EventType          interface{} `json:"event_type"`
	EventTypePrefix    interface{} `json:"event_type_prefix"`
	SourceLayer        interface{} `json:"source_layer"`
	SourceID           interface{} `json:"source_id"`
	SourceParentID     interface{} `json:"source_parent_id"`
}

type ListRequestStreamEventsRow struct {
	SequenceNumber int64  `json:"sequence_number"`
	RawEventJson   string `json:"raw_event_json"`
}

func (q *Queries) ListRequestStreamEvents(ctx context.Context, arg ListRequestStreamEventsParams) ([]ListRequestStreamEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestStreamEvents,
		arg.RequestID,
		arg.FromSequenceNumber,
		arg.RunnerID,
		arg.NodeID,
		arg.SessionID,
		arg.Status,
		arg.EventType,
		arg.EventTypePrefix,
		arg.SourceLayer,
		arg.SourceID,
		arg.SourceParentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestStreamEventsRow
	for rows.Next() {
		var i ListRequestStreamEventsRow
		if err := rows.Scan(&i.SequenceNumber, &i.RawEventJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerRecords = `-- name: ListRunnerRecords :many
SELECT sequence_number, kind, record_json
FROM runner_records
WHERE runner_id = ?1
ORDER BY sequence_number ASC
`

type ListRunnerRecordsRow struct {
	SequenceNumber int64  `json:"sequence_number"`
	Kind           string `json:"kind"`
	RecordJson     string `json:"record_json"`
}

func (q *Queries) ListRunnerRecords(ctx context.Context, runnerID string) ([]ListRunnerRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunnerRecords, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnerRecordsRow
	for rows.Next() {
		var i ListRunnerRecordsRow
		if err := rows.Scan(&i.SequenceNumber, &i.Kind, &i.RecordJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, status, request, dag_json, created, updated
FROM tasks
ORDER BY updated DESC, created DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Request,
			&i.DagJson,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT name, image, config_json, registered
FROM tools
ORDER BY name ASC
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.QueryContext(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.Name,
			&i.Image,
			&i.ConfigJson,
			&i.Registered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEdgeResult = `-- name: UpdateEdgeResult :execrows
UPDATE edges
SET
  status = ?1,
  handoff_yaml = ?2,
  finished = ?3
WHERE id = ?4
`

type UpdateEdgeResultParams struct {
	Status      string         `json:"status"`
	HandoffYaml sql.NullString `json:"handoff_yaml"`
	Finished    sql.NullString `json:"finished"`
	EdgeID      string         `json:"edge_id"`
}

func (q *Queries) UpdateEdgeResult(ctx context.Context, arg UpdateEdgeResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEdgeResult,
		arg.Status,
		arg.HandoffYaml,
		arg.Finished,
		arg.EdgeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskPlan = `-- name: UpdateTaskPlan :execrows
UPDATE tasks
SET
  status = ?1,
  dag_json = ?2,
  updated = CURRENT_TIMESTAMP
WHERE id = ?3
`

type UpdateTaskPlanParams struct {
	Status  string         `json:"status"`
	DagJson sql.NullString `json:"dag_json"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateTaskPlan(ctx context.Context, arg UpdateTaskPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskPlan, arg.Status, arg.DagJson, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execrows
UPDATE tasks
SET status = ?1, updated = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEdge = `-- name: UpsertEdge :exec
INSERT INTO edges (
  id,
  task_id,
  tool_name,
  upstream,
  status,
  shared_dir,
  handoff_yaml,
  started,
  finished
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
ON CONFLICT(id) DO UPDATE SET
  task_id = excluded.task_id,
  tool_name = excluded.tool_name,
  upstream = excluded.upstream,
  status = excluded.status,
  shared_dir = excluded.shared_dir,
  handoff_yaml = excluded.handoff_yaml,
  started = excluded.started,
  finished = excluded.finished
`

type UpsertEdgeParams struct {
	ID          string         `json:"id"`
	TaskID      string         `json:"task_id"`
	ToolName    string         `json:"tool_name"`
	Upstream    sql.NullString `json:"upstream"`
	Status      string         `json:"status"`
	SharedDir   sql.NullString `json:"shared_dir"`
	HandoffYaml sql.NullString `json:"handoff_yaml"`
	Started     sql.NullString `json:"started"`
	Finished    sql.NullString `json:"finished"`
}

func (q *Queries) UpsertEdge(ctx context.Context, arg UpsertEdgeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEdge,
		arg.ID,
		arg.TaskID,
		arg.ToolName,
		arg.Upstream,
		arg.Status,
		arg.SharedDir,
		arg.HandoffYaml,
		arg.Started,
		arg.Finished,
	)
	return err
}

const upsertSnapshotCursor = `-- name: UpsertSnapshotCursor :exec
INSERT INTO snapshot_cursors (
  request_id,
  runner_id,
  checkpoint_sequence,
  event_sequence,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
ON CONFLICT(request_id) DO UPDATE SET
  runner_id = excluded.runner_id,
  checkpoint_sequence = excluded.checkpoint_sequence,
  event_sequence = excluded.event_sequence,
  updated_at = excluded.updated_at
`

type UpsertSnapshotCursorParams struct {
	RequestID          string         `json:"request_id"`
	RunnerID           sql.NullString `json:"runner_id"`
	CheckpointSequence int64          `json:"checkpoint_sequence"`
	EventSequence      int64          `json:"event_sequence"`
	UpdatedAt          string         `json:"updated_at"`
}

func (q *Queries) UpsertSnapshotCursor(ctx context.Context, arg UpsertSnapshotCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshotCursor,
		arg.RequestID,
		arg.RunnerID,
		arg.CheckpointSequence,
		arg.EventSequence,
		arg.UpdatedAt,
	)
	return err
}

const upsertTool = `-- name: UpsertTool :exec
INSERT INTO tools (name, image, config_json)
VALUES (?1, ?2, ?3)
ON CONFLICT(name) DO UPDATE SET
  image = excluded.image,
  config_json = excluded.config_json,
  registered = CURRENT_TIMESTAMP
`

type UpsertToolParams struct {
	Name       string `json:"name"`
	Image      string `json:"image"`
	ConfigJson string `json:"config_json"`
}

func (q *Queries) UpsertTool(ctx context.Context, arg UpsertToolParams) error {
	_, err := q.db.ExecContext(ctx, upsertTool, arg.Name, arg.Image, arg.ConfigJson)
	return err
}
