package runner

import (
	"context"
	"errors"
	"time"
)

// Agent is the execution contract a [Node] needs across the runner's
// phased lifecycle.
//
// Execute runs the node's main unit of work. Polish is invoked once during
// [PhasePolishing] to collect a preview/plan fragment the runner reviews
// through its planner skill. Report is invoked once during [PhaseReport]
// after a successful execution and is expected to summarize the node's
// output.
//
// Implementations should treat ctx cancellation in each method as the
// signal to abort promptly and return ctx.Err.
type Agent interface {
	Execute(ctx context.Context, parentOutputs map[string]any) (output any, newNodes []*Node, err error)
	Polish(ctx context.Context) (fragment any, err error)
	Report(ctx context.Context, output any) (summary any, err error)
}

// EventType defines internal engine lifecycle events persisted by the runner
// and normalized into compact stream events.
type EventType uint8

const (
	EventNodeAdded EventType = iota
	EventNodeStarted
	EventNodeCompleted
	EventNodeFailed
	EventEngineIdle
	EventEngineStopped
)

func (e EventType) String() string {
	switch e {
	case EventNodeAdded:
		return "NodeAdded"
	case EventNodeStarted:
		return "NodeStarted"
	case EventNodeCompleted:
		return "NodeCompleted"
	case EventNodeFailed:
		return "NodeFailed"
	case EventEngineIdle:
		return "EngineIdle"
	case EventEngineStopped:
		return "EngineStopped"
	default:
		return "Unknown"
	}
}

// RunnerEvent represents an internal graph execution state change.
type RunnerEvent struct {
	Type   EventType
	NodeID string
	Data   any // Output for Completed, err for Failed
}

// RunnerSnapshot is a queryable freeze-frame of the engine's state.
type RunnerSnapshot struct {
	ActiveCount    int
	CompletedNodes map[string]any
	PendingNodes   map[string]int
	GraphEdges     map[string][]string // parent -> children IDs
	NodesData      map[string]*Node    // Make nodes accessible for snapshot reading
}

// RunnerStatus reports the current lifecycle state of a Runner.
type RunnerStatus string

const (
	RunnerStatusPending  RunnerStatus = "pending"
	RunnerStatusRunning  RunnerStatus = "running"
	RunnerStatusIdle     RunnerStatus = "idle"
	RunnerStatusFailed   RunnerStatus = "failed"
	RunnerStatusCanceled RunnerStatus = "canceled"
)

// RunnerState is the externally visible lifecycle snapshot of a Runner.
type RunnerState struct {
	Status     RunnerStatus `json:"status" yaml:"status"`
	StartedAt  time.Time    `json:"started_at,omitempty" yaml:"started_at,omitempty"`
	UpdatedAt  time.Time    `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	FinishedAt time.Time    `json:"finished_at,omitempty" yaml:"finished_at,omitempty"`
	Error      string       `json:"error,omitempty" yaml:"error,omitempty"`
}

// SkillSummary describes one skill the planner may reference when producing
// or revising a [CoarsePlan].
type SkillSummary struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

// RunnerPhase reports which high-level business stage of the plan lifecycle a
// Runner is currently in.
//
// RunnerPhase is orthogonal to [RunnerStatus]: Status describes the engine's
// running/idle/terminal state, while Phase describes the plan pipeline stage
// (polish → review → execute → settled).
//
// The runner may transition through polishing, review, replan, execute,
// and report before settling, depending on which entry points callers use.
type RunnerPhase string

const (
	// PhaseCreated is the initial phase of a newly constructed runner.
	PhaseCreated RunnerPhase = "created"
	// PhasePolishing is entered while agents concurrently produce their
	// polish fragments. Not yet used by the engine.
	PhasePolishing RunnerPhase = "polishing"
	// PhaseAwaitingReview is entered after polish fragments are collected
	// and the runner is waiting for planner review.
	PhaseAwaitingReview RunnerPhase = "awaiting_review"
	// PhaseAwaitingReplan is entered when polish is rejected and the plan
	// must be regenerated by the runner's planner skill.
	PhaseAwaitingReplan RunnerPhase = "awaiting_replan"
	// PhaseExecuting is entered while the runner is driving the DAG
	// through its event loop.
	PhaseExecuting RunnerPhase = "executing"
	// PhaseReport is entered after the DAG settles successfully. The
	// runner fans [Agent.Report] across every completed node to
	// collect per-node summaries before transitioning to [PhaseSettled].
	PhaseReport RunnerPhase = "report"
	// PhaseSettled is the terminal phase. A runner reaches PhaseSettled
	// after [Runner.Abort], after a node failure, or after a cooperative
	// completion path in which [Runner.Complete] drives the runner from
	// [PhaseExecuting] through [PhaseReport] into the terminal state.
	PhaseSettled RunnerPhase = "settled"
)

// ErrRunnerAlreadyStarted is returned when callers attempt to start or
// configure persistence on a Runner that has already started.
var ErrRunnerAlreadyStarted = errors.New("orchestrate: runner already started")

// ErrInvalidPhase is returned when a phased-lifecycle transition is
// invoked from the wrong [RunnerPhase].
var ErrInvalidPhase = errors.New("orchestrate: runner in wrong phase for this transition")

// ErrPlanRequired is returned when a phased-lifecycle transition is
// invoked on a runner that was not constructed with [Setup.Plan].
var ErrPlanRequired = errors.New("orchestrate: runner has no plan attached")
