package runner

import (
	"context"
	"errors"
	"time"
)

// Executor is the minimal execution contract a Node needs.
type Executor interface {
	Execute(ctx context.Context, parentOutputs map[string]any) (output any, newNodes []*Node, err error)
}

// EventType defines the lifecycle events published by the runner.
type EventType uint8

const (
	EventNodeAdded EventType = iota
	EventNodeStarted
	EventNodeCompleted
	EventNodeFailed
	EventEngineIdle
	EventEngineStopped
)

func (e EventType) String() string {
	switch e {
	case EventNodeAdded:
		return "NodeAdded"
	case EventNodeStarted:
		return "NodeStarted"
	case EventNodeCompleted:
		return "NodeCompleted"
	case EventNodeFailed:
		return "NodeFailed"
	case EventEngineIdle:
		return "EngineIdle"
	case EventEngineStopped:
		return "EngineStopped"
	default:
		return "Unknown"
	}
}

// RunnerEvent represents a notification regarding graph execution states.
type RunnerEvent struct {
	Type   EventType
	NodeID string
	Data   any // Output for Completed, err for Failed
}

// RunnerSnapshot is a queryable freeze-frame of the engine's state.
type RunnerSnapshot struct {
	ActiveCount    int
	CompletedNodes map[string]any
	PendingNodes   map[string]int
	GraphEdges     map[string][]string // parent -> children IDs
	NodesData      map[string]*Node    // Make nodes accessible for snapshot reading
}

// RunnerStatus reports the current lifecycle state of a Runner.
type RunnerStatus string

const (
	RunnerStatusPending  RunnerStatus = "pending"
	RunnerStatusRunning  RunnerStatus = "running"
	RunnerStatusIdle     RunnerStatus = "idle"
	RunnerStatusFailed   RunnerStatus = "failed"
	RunnerStatusCanceled RunnerStatus = "canceled"
)

// RunnerState is the externally visible lifecycle snapshot of a Runner.
type RunnerState struct {
	Status     RunnerStatus `json:"status" yaml:"status"`
	StartedAt  time.Time    `json:"started_at,omitempty" yaml:"started_at,omitempty"`
	UpdatedAt  time.Time    `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	FinishedAt time.Time    `json:"finished_at,omitempty" yaml:"finished_at,omitempty"`
	Error      string       `json:"error,omitempty" yaml:"error,omitempty"`
}

// RunnerPhase reports which high-level business stage of the plan lifecycle a
// Runner is currently in.
//
// RunnerPhase is orthogonal to [RunnerStatus]: Status describes the engine's
// running/idle/terminal state, while Phase describes the plan pipeline stage
// (polish → review → execute → settled).
//
// The polishing, awaiting-review, and awaiting-replan phases are declared now
// as part of the interface surface; the current runner only transitions
// Created → Executing → Settled. Future work fills in the polish/review
// path without changing this enum.
type RunnerPhase string

const (
	// PhaseCreated is the initial phase of a newly constructed runner.
	PhaseCreated RunnerPhase = "created"
	// PhasePolishing is entered while executors concurrently produce their
	// polish fragments. Not yet used by the engine.
	PhasePolishing RunnerPhase = "polishing"
	// PhaseAwaitingReview is entered after polish fragments are collected
	// and the runner is waiting for an orchestrator review. Not yet used.
	PhaseAwaitingReview RunnerPhase = "awaiting_review"
	// PhaseAwaitingReplan is entered when polish is rejected and the plan
	// must be regenerated by the orchestrator. Not yet used.
	PhaseAwaitingReplan RunnerPhase = "awaiting_replan"
	// PhaseExecuting is entered while the runner is driving the DAG
	// through its event loop.
	PhaseExecuting RunnerPhase = "executing"
	// PhaseSettled is the terminal phase. The current engine reaches
	// PhaseSettled only when its context is canceled or a node fails;
	// reaching idle does not by itself settle the runner because the
	// engine continues to accept dynamically added nodes. Future phases
	// (polish/review) will introduce a cooperative settle path.
	PhaseSettled RunnerPhase = "settled"
)

// Node represents a single unit of work within the Runner's execution graph.
type Node struct {
	Id      string  `json:"id" yaml:"id"`
	Parents []*Node `json:"parents,omitempty" yaml:"parents,omitempty"`
	// Executor contains the execution logic of the node.
	Executor Executor `json:"-" yaml:"-"`

	CreatedAt  time.Time `json:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `json:"updated_at" yaml:"updated_at"`
	FinishedAt time.Time `json:"finished_at" yaml:"finished_at"`
}

type executionResult struct {
	nodeID   string
	output   any
	newNodes []*Node
	err      error
}

// ErrRunnerAlreadyStarted is returned when callers attempt to start or
// configure persistence on a Runner that has already started.
var ErrRunnerAlreadyStarted = errors.New("orchestrate: runner already started")
