package cli

import (
	"fmt"
	"os"
	"path/filepath"
)

type builtinDemoTool struct {
	Name    string
	ToolYML string
	RunSH   string
}

var builtinDemoTools = []builtinDemoTool{
	{
		Name: "toy-brief",
		ToolYML: `name: "toy-brief"
version: "0.1.0"
description: "Builds a compact execution brief from the original request"
input_types: ["request"]
output_types: ["brief"]
model: "demo/toy-brief"
defaults:
  style: "concise"
`,
		RunSH: `#!/bin/sh
set -eu

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
mkdir -p "${OUTPUT_PATH}"

request_text="$(awk '
  $0 == "## Original Request" {capture=1; next}
  /^## / && capture {exit}
  capture {print}
' "${SUB_TASK}")"

if [ -z "${request_text}" ]; then
  request_text="(empty request)"
fi

cat > "${OUTPUT_PATH}/brief.md" <<EOF
# Demo Brief

## Original Request

${request_text}

## Normalized Intent

- Produce a small, review-friendly demo artifact chain.
- Keep outputs textual and easy to inspect.
- Preserve the request language when possible.

## Suggested Next Step

Expand this brief into a more structured draft for human review.
EOF

cat > "${OUTPUT_PATH}/_handoff.md" <<EOF
---
task_id: "${TASK_ID}"
tool: "toy-brief"
status: "completed"
output_files:
  - brief.md
next_tool: "toy-drafter"
timestamp: "${timestamp}"
---

## Description

Created a normalized brief from the original request so the next tool can draft a deliverable.
EOF
`,
	},
	{
		Name: "toy-drafter",
		ToolYML: `name: "toy-drafter"
version: "0.1.0"
description: "Expands the upstream brief into a structured draft artifact"
input_types: ["brief"]
output_types: ["draft"]
model: "demo/toy-drafter"
defaults:
  format: "markdown"
`,
		RunSH: `#!/bin/sh
set -eu

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
mkdir -p "${OUTPUT_PATH}"

brief_file="$(find "${INPUT_PATH}" -type f -name 'brief.md' | sort | head -n 1)"
if [ -z "${brief_file}" ]; then
  echo "brief.md not found in INPUT_PATH=${INPUT_PATH}" >&2
  exit 1
fi

cat > "${OUTPUT_PATH}/draft.md" <<EOF
# Draft Deliverable

This file was generated by toy-drafter.

## Upstream Brief

$(cat "${brief_file}")

## Draft Sections

1. Goal
2. Proposed flow
3. Output checklist

## Notes

This is a toy draft intended only to prove the orchestration flow.
EOF

cat > "${OUTPUT_PATH}/_handoff.md" <<EOF
---
task_id: "${TASK_ID}"
tool: "toy-drafter"
status: "completed"
output_files:
  - draft.md
next_tool: "toy-packager"
timestamp: "${timestamp}"
---

## Description

Expanded the brief into a structured draft for the terminal packaging stage.
EOF
`,
	},
	{
		Name: "toy-packager",
		ToolYML: `name: "toy-packager"
version: "0.1.0"
description: "Packages the draft into final demo artifacts and a small manifest"
input_types: ["draft"]
output_types: ["final"]
model: "demo/toy-packager"
defaults:
  manifest: true
`,
		RunSH: `#!/bin/sh
set -eu

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
mkdir -p "${OUTPUT_PATH}"

draft_file="$(find "${INPUT_PATH}" -type f -name 'draft.md' | sort | head -n 1)"
if [ -z "${draft_file}" ]; then
  echo "draft.md not found in INPUT_PATH=${INPUT_PATH}" >&2
  exit 1
fi

cat > "${OUTPUT_PATH}/final-report.md" <<EOF
# Final Demo Report

This is the terminal artifact produced by the dango demo pipeline.

## Included Draft

$(cat "${draft_file}")

## Packaging Result

- Final artifact generated successfully
- Ready for human inspection
- Pipeline contract satisfied with _handoff.md
EOF

cat > "${OUTPUT_PATH}/manifest.json" <<EOF
{
  "task_id": "${TASK_ID}",
  "tool": "toy-packager",
  "generated_at": "${timestamp}",
  "artifacts": [
    "final-report.md",
    "manifest.json"
  ]
}
EOF

cat > "${OUTPUT_PATH}/_handoff.md" <<EOF
---
task_id: "${TASK_ID}"
tool: "toy-packager"
status: "completed"
output_files:
  - final-report.md
  - manifest.json
next_tool: null
timestamp: "${timestamp}"
---

## Description

Packaged the draft into terminal demo artifacts for final inspection.
EOF
`,
	},
}

func materializeBuiltinDemoTools(dataDir string) (string, error) {
	root := filepath.Join(dataDir, "_builtin_demo_tools")
	for _, tool := range builtinDemoTools {
		toolDir := filepath.Join(root, tool.Name)
		if err := os.MkdirAll(toolDir, 0o755); err != nil {
			return "", fmt.Errorf("create builtin demo tool dir %q: %w", toolDir, err)
		}

		toolPath := filepath.Join(toolDir, "tool.yaml")
		if err := os.WriteFile(toolPath, []byte(tool.ToolYML), 0o644); err != nil {
			return "", fmt.Errorf("write builtin demo tool spec %q: %w", toolPath, err)
		}

		runPath := filepath.Join(toolDir, "run")
		if err := os.WriteFile(runPath, []byte(tool.RunSH), 0o755); err != nil {
			return "", fmt.Errorf("write builtin demo tool run hook %q: %w", runPath, err)
		}
		if err := os.Chmod(runPath, 0o755); err != nil {
			return "", fmt.Errorf("chmod builtin demo tool run hook %q: %w", runPath, err)
		}
	}

	return root, nil
}
