// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Edge struct {
	ID          string         `json:"id"`
	TaskID      string         `json:"task_id"`
	ToolName    string         `json:"tool_name"`
	Upstream    sql.NullString `json:"upstream"`
	Status      string         `json:"status"`
	SharedDir   sql.NullString `json:"shared_dir"`
	HandoffYaml sql.NullString `json:"handoff_yaml"`
	Started     sql.NullString `json:"started"`
	Finished    sql.NullString `json:"finished"`
}

type Log struct {
	ID        int64     `json:"id"`
	EdgeID    string    `json:"edge_id"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

type RequestStreamEvent struct {
	RequestID      string         `json:"request_id"`
	SequenceNumber int64          `json:"sequence_number"`
	LogicalTime    int64          `json:"logical_time"`
	EventType      string         `json:"event_type"`
	SourceLayer    string         `json:"source_layer"`
	SourceID       sql.NullString `json:"source_id"`
	SourceParentID sql.NullString `json:"source_parent_id"`
	RunnerID       sql.NullString `json:"runner_id"`
	NodeID         sql.NullString `json:"node_id"`
	SessionID      sql.NullString `json:"session_id"`
	Status         string         `json:"status"`
	Timestamp      string         `json:"timestamp"`
	RawEventJson   string         `json:"raw_event_json"`
}

type Task struct {
	ID      string         `json:"id"`
	Status  string         `json:"status"`
	Request sql.NullString `json:"request"`
	DagJson sql.NullString `json:"dag_json"`
	Created string         `json:"created"`
	Updated string         `json:"updated"`
}

type Tool struct {
	Name       string `json:"name"`
	Image      string `json:"image"`
	ConfigJson string `json:"config_json"`
	Registered string `json:"registered"`
}
