// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, status, request, dag_json)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
`

type CreateTaskParams struct {
	ID      string         `json:"id"`
	Status  string         `json:"status"`
	Request sql.NullString `json:"request"`
	DagJson sql.NullString `json:"dag_json"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.Status,
		arg.Request,
		arg.DagJson,
	)
	return err
}

const deleteTool = `-- name: DeleteTool :execrows
DELETE FROM tools
WHERE name = ?1
`

func (q *Queries) DeleteTool(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTool, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT id, status, request, dag_json, created, updated
FROM tasks
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Request,
		&i.DagJson,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getTool = `-- name: GetTool :one
SELECT name, image, config_json, registered
FROM tools
WHERE name = ?1
LIMIT 1
`

func (q *Queries) GetTool(ctx context.Context, name string) (Tool, error) {
	row := q.db.QueryRowContext(ctx, getTool, name)
	var i Tool
	err := row.Scan(
		&i.Name,
		&i.Image,
		&i.ConfigJson,
		&i.Registered,
	)
	return i, err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO logs (edge_id, level, message)
VALUES (?1, ?2, ?3)
`

type InsertLogParams struct {
	EdgeID  string `json:"edge_id"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog, arg.EdgeID, arg.Level, arg.Message)
	return err
}

const listTools = `-- name: ListTools :many
SELECT name, image, config_json, registered
FROM tools
ORDER BY name ASC
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.QueryContext(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.Name,
			&i.Image,
			&i.ConfigJson,
			&i.Registered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEdgeResult = `-- name: UpdateEdgeResult :execrows
UPDATE edges
SET
  status = ?1,
  handoff_yaml = ?2,
  finished = ?3
WHERE id = ?4
`

type UpdateEdgeResultParams struct {
	Status      string         `json:"status"`
	HandoffYaml sql.NullString `json:"handoff_yaml"`
	Finished    sql.NullString `json:"finished"`
	EdgeID      string         `json:"edge_id"`
}

func (q *Queries) UpdateEdgeResult(ctx context.Context, arg UpdateEdgeResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEdgeResult,
		arg.Status,
		arg.HandoffYaml,
		arg.Finished,
		arg.EdgeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskPlan = `-- name: UpdateTaskPlan :execrows
UPDATE tasks
SET
  status = ?1,
  dag_json = ?2,
  updated = CURRENT_TIMESTAMP
WHERE id = ?3
`

type UpdateTaskPlanParams struct {
	Status  string         `json:"status"`
	DagJson sql.NullString `json:"dag_json"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateTaskPlan(ctx context.Context, arg UpdateTaskPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskPlan, arg.Status, arg.DagJson, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execrows
UPDATE tasks
SET status = ?1, updated = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEdge = `-- name: UpsertEdge :exec
INSERT INTO edges (
  id,
  task_id,
  tool_name,
  upstream,
  status,
  shared_dir,
  handoff_yaml,
  started,
  finished
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
ON CONFLICT(id) DO UPDATE SET
  task_id = excluded.task_id,
  tool_name = excluded.tool_name,
  upstream = excluded.upstream,
  status = excluded.status,
  shared_dir = excluded.shared_dir,
  handoff_yaml = excluded.handoff_yaml,
  started = excluded.started,
  finished = excluded.finished
`

type UpsertEdgeParams struct {
	ID          string         `json:"id"`
	TaskID      string         `json:"task_id"`
	ToolName    string         `json:"tool_name"`
	Upstream    sql.NullString `json:"upstream"`
	Status      string         `json:"status"`
	SharedDir   sql.NullString `json:"shared_dir"`
	HandoffYaml sql.NullString `json:"handoff_yaml"`
	Started     sql.NullString `json:"started"`
	Finished    sql.NullString `json:"finished"`
}

func (q *Queries) UpsertEdge(ctx context.Context, arg UpsertEdgeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEdge,
		arg.ID,
		arg.TaskID,
		arg.ToolName,
		arg.Upstream,
		arg.Status,
		arg.SharedDir,
		arg.HandoffYaml,
		arg.Started,
		arg.Finished,
	)
	return err
}

const upsertTool = `-- name: UpsertTool :exec
INSERT INTO tools (name, image, config_json)
VALUES (?1, ?2, ?3)
ON CONFLICT(name) DO UPDATE SET
  image = excluded.image,
  config_json = excluded.config_json,
  registered = CURRENT_TIMESTAMP
`

type UpsertToolParams struct {
	Name       string `json:"name"`
	Image      string `json:"image"`
	ConfigJson string `json:"config_json"`
}

func (q *Queries) UpsertTool(ctx context.Context, arg UpsertToolParams) error {
	_, err := q.db.ExecContext(ctx, upsertTool, arg.Name, arg.Image, arg.ConfigJson)
	return err
}
